---
    - name: generate qr codes images
      command: "qrencode -o ./media/qr_images/{{ item.0.grafana_code }}-{{ item.1 }}.png 'https://firma.rentabasicauniversal.es/' -m 2 -s 6"
      loop: "{{ qr_list|subelements('qr_codes') }}"

    - debug:
        var: phrases
      tags: template

    - name: generate poster adoc from template
      template:
        src: "poster.adoc.j2"
        dest: "./media/posters/adoc/{{ item.grafana_code }}.adoc"
      loop: "{{ qr_list }}"
      tags: template

    - name: Generate PDF document
      command: "asciidoctor-pdf -a pdf-stylesdir=./common-resources/themes -a pdf-fontsdir=./common-resources/fonts -o ./media/posters/pdf/{{ item.grafana_code }}.pdf ./media/posters/adoc/{{ item.grafana_code }}.adoc"
      ignore_errors: yes
      loop: "{{ qr_list }}"
