---
    - name: provisioning config
      copy:
        src: dashboards_provisioner.yaml
        dest: /var/lib/docker/volumes/ecimonitoring_grafana-dashboards/_data/dashboards/dashboards_provisioner.yaml

    - name: generate dashboard
      template:
        src: qr_counter.json.j2
        dest: "/var/lib/docker/volumes/ecimonitoring_grafana-dashboards-json/_data/qr_codes_spain/qr_counter_{{ item.grafana_code }}.json"
      loop: "{{ qr_list }}"
      tags: counter

    - name: create nc script to feed graphite
      template:
        src: qr_counter.sh.j2
        dest: "/root/eci-grafana/eci-monitoring/graphite/eci/qr_counters/{{ item.grafana_code }}.sh"
        mode: 0755
      loop: "{{ qr_list }}"
      tags: graphite

    - name: cronjob that updates graphite each 5 minutos
      cron:
        name: "update graphite qr counters"
        minute: "*/5"
        job: "/root/eci-grafana/eci-monitoring/graphite/eci/qr_counters/*"
      tags: graphite
