- hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars.yaml

  tasks:

    - name: insert random grafana code into qr_list per user
      set_fact:
        qr_list_aux: "{{ qr_list_aux | default([]) + [ new_item ] }}"
      vars:
        new_item:      
          number_of_posters: "{{ item.number_of_posters }}"
          email: "{{ item.email }}"
          grafana_code: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
      loop: "{{ qr_list }}"

    - name: debug
      debug: 
        msg: "{{ item }}"
      loop: "{{ qr_list_aux }}"

    - name: generate qr_ids
      set_fact:
        qr_list_aux2: "{{ qr_list_aux2 | default([]) + [ new_item ] }}"
      vars:
        new_item:
          number_of_posters: "{{ item.number_of_posters }}"
          email: "{{ item.email }}"
          grafana_code: "{{ item.grafana_code }}"
          qr_codes: "{{ range(0, item.number_of_posters  | int) | list }}"
      loop: "{{ qr_list_aux }}"

    - name: debug
      debug:
        msg: "{{ item }}"
      loop: "{{ qr_list_aux2 }}"


    - name: create vars.yml 
      template:
        src: final_list.yaml.j2
        dest: final_list.yaml
