- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - final_list.yaml
    - vault_vars.yaml

  roles:
    - role: qr_generator
      tags: qr
    - role: grafana_provisioner
      tags: grafana
